
services:
  backend:
    build:
      context: ./NextSite.Server
      dockerfile: Dockerfile
    container_name: nextsite-server
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8080:8080"
    networks:
      - nextsite-network
    restart: unless-stopped

  frontend:
    build:
      context: ./nextsite.client
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:8080 # change for cloud deployment
    container_name: nextsite-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - nextsite-network
    restart: unless-stopped

networks:
  nextsite-network:
    driver: bridge
